name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

env:
  CONTAINER_APP_NAME: insightnet
  CONTAINER_APP_RG: insightnet-rg

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
      runs-on: ubuntu-latest
      if: ${{ github.event.workflow_run.conclusion == 'success' }}

      steps:
          - name: Azure Login
            uses: azure/login@v3
            with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

          - name: Set short SHA
            run: echo "TAG=$(echo ${{ github.event.workflow_run.head_sha }} | cut -c1-7)" >> $GITHUB_ENV

          - name: Update Azure Container Apps with new docker image
            run: az containerapp update --name $CONTAINER_APP_NAME --resource-group $CONTAINER_APP_RG --image docker.io/zachathanasiadis/cc:insightnet-${{ env.TAG }}

          - name: Get FQDN of the app
            run: |
              echo "FQDN=$(az containerapp show \
              --name $CONTAINER_APP_NAME \
              --resource-group $CONTAINER_APP_RG \
              --query properties.configuration.ingress.fqdn \
              -o tsv)" >> $GITHUB_ENV

          - name: Health check
            run: |
              curl \
                --fail \
                --silent \
                --show-error \
                --retry 10 \
                --retry-delay 10 \
                --retry-all-errors \
                https://${FQDN}/health