name: CI

on:
    push:
        branches: [main]
        paths:
          - "src/**"
          - "tests/**"
          - "Dockerfile"
          - "pyproject.toml"
          - "poetry.lock"
    pull_request:
        branches: [main]
        paths:
          - "src/**"
          - "tests/**"
          - "Dockerfile"
          - "pyproject.toml"
          - "poetry.lock"

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install Poetry
              run: pip install poetry poetry-plugin-export

            - name: Export requirements.txt from Poetry
              run: poetry export -f requirements.txt --without-hashes --output requirements.txt --with dev

            - name: Install dependencies
              run: pip install -r requirements.txt

            - name: Install project
              run: pip install -e .

            - name: Install mypy, bandit, autopep8 and Ruff
              run: pip install mypy bandit autopep8 ruff

            - name: Static type checking with mypy
              run: mypy src tests

            - name: Security analysis with bandit (report MEDIUM+ severity and confidence)
              run: bandit -r src -ll -ii

            - name: Check code style with autopep8
              run: autopep8 --recursive --diff src tests

            - name: Lint with Ruff
              run: ruff check src tests

            - name: Run tests
              run: pytest tests
