name: CI

on:
    push:
        paths:
          - "src/**"
          - "tests/**"
          - "Dockerfile"
          - "pyproject.toml"
          - "poetry.lock"
    pull_request:
        paths:
          - "src/**"
          - "tests/**"
          - "Dockerfile"
          - "pyproject.toml"
          - "poetry.lock"
    workflow_dispatch:

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: "3.13"

            - name: Install Poetry
              run: pip install poetry 

            - name: Configure Poetry
              run: poetry config virtualenvs.create false

            - name: Install dependencies
              run: poetry install --with dev

            - name: Static type checking with mypy
              run: poetry run mypy src tests

            - name: Security analysis with bandit (report MEDIUM+ severity and confidence)
              run: poetry run bandit -r src -ll -ii

            - name: Check code style with autopep8
              run: poetry run autopep8 --recursive --diff src tests

            - name: Lint with Ruff
              run: poetry run ruff check src tests

            - name: Run tests
              run: poetry run pytest tests

    docker:
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        needs: test
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Set short SHA
              run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV

            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                username: zachathanasiadis
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v7
              with:
                push: true
                tags: |
                 zachathanasiadis/cc:insightnet-latest
                 zachathanasiadis/cc:insightnet-${{ env.SHORT_SHA }}
